spring.application.name=whatsaAppchatbot
firebase.database.url=https://<WhatsaApp>.firebaseio.com
# File: application.properties
# WhatsApp Cloud API
# application.properties
whatsapp.api.url=https://graph.facebook.com/v18.0/669173112950971/messages
whatsapp.api.token=EAAZAjeb86b2IBO4XOFTrUB00ZCbl1Qo0iwZB28L6ynzM35EERny4PQ2MZCsrEr2CTnor9DrhCjXdTHdvV5ZC1RQdoAUZBfItlzvbtBMCSsI3N0kZBke2548Ujz23IpRV1W2I1HZAVhqGEjLtLJjD7YfrJEX7aFxdhHjQSlY7ZBalPZBJWU8YNTZAzHZBiMFIcgtASteXN9aDgO1ppiALkXOG74SLoQM21czNPFRuhUoZD
verify.token=sneha_verify_token_123
# Server
server.port=8080



